/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Friday, November 18, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#include "tcldom-libxml2.h"

/*
 * Remove macros that will interfere with the definitions below.
 */


/*
 * WARNING: The contents of this file is automatically generated by the
 * genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the tcldomxml.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

TcldomxmlStubs tcldomxmlStubs = {
    TCL_STUB_MAGIC,
    NULL,
    Tcldomxml_Init, /* 0 */
    NULL, /* 1 */
    TclDOM_NewDoc, /* 2 */
    TclDOM_CreateObjFromNode, /* 3 */
    TclDOM_CreateObjFromDoc, /* 4 */
    TclDOM_GetNodeFromObj, /* 5 */
    TclDOM_GetDocFromObj, /* 6 */
};

/* !END!: Do not edit above this line. */
