/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Tuesday, September 12, 2023.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#include "itk.h"

/*
 * Remove macros that will interfere with the definitions below.
 */

/*
 * WARNING: The contents of this file is automatically generated by the
 * tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the generic/itk.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

ItkStubs itkStubs = {
    TCL_STUB_MAGIC,
    NULL,
    Itk_Init, /* 0 */
    Itk_SafeInit, /* 1 */
    Itk_ConfigBodyCmd, /* 2 */
    Itk_UsualCmd, /* 3 */
    Itk_ClassOptionDefineCmd, /* 4 */
    Itk_ClassOptionIllegalCmd, /* 5 */
    Itk_ConfigClassOption, /* 6 */
    Itk_CreateClassOptTable, /* 7 */
    Itk_FindClassOptTable, /* 8 */
    NULL, /* 9 */
    Itk_CreateClassOption, /* 10 */
    Itk_FindClassOption, /* 11 */
    Itk_DelClassOption, /* 12 */
    Itk_ArchetypeInit, /* 13 */
    Itk_OptListInit, /* 14 */
    Itk_OptListFree, /* 15 */
    Itk_OptListAdd, /* 16 */
    Itk_OptListRemove, /* 17 */
};

/* !END!: Do not edit above this line. */
