[package]
name = "papers-view"
version = "0.1.0"
license = "MIT"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true
# For build.rs scripts
rustc-args = ["--cfg", "docsrs"]
# For rustdoc
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["v48"]
v46 = ["papers-view-sys/v46", "papers-view-sys/v42"]
v48 = ["papers-view-sys/v48", "v46"]
v49 = ["papers-view-sys/v49", "v48"]

[dependencies]
papers-document.workspace = true
papers-view-sys.workspace = true
libc = "0.2"
bitflags = "2.2"
glib.workspace = true
gio.workspace = true
gdk-pixbuf.workspace = true
gtk.workspace = true
gdk.workspace = true
