/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Thursday, August 3, 2023.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from OTAccountSettings.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

@class OTWalrus;
@class OTWebAccess;

#ifdef __cplusplus
#define OTACCOUNTSETTINGS_FUNCTION extern "C"
#else
#define OTACCOUNTSETTINGS_FUNCTION extern
#endif

/** If adding/updating any fields to AccountSettings, make sure to also update the OTAccountMetadataClassC.proto entry as well */
@interface OTAccountSettings : PBCodable <NSCopying>
{
    OTWalrus *_walrus;
    OTWebAccess *_webAccess;
}


@property (nonatomic, readonly) BOOL hasWalrus;
@property (nonatomic, retain) OTWalrus *walrus;

@property (nonatomic, readonly) BOOL hasWebAccess;
@property (nonatomic, retain) OTWebAccess *webAccess;

// Performs a shallow copy into other
- (void)copyTo:(OTAccountSettings *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(OTAccountSettings *)other;

OTACCOUNTSETTINGS_FUNCTION BOOL OTAccountSettingsReadFrom(__unsafe_unretained OTAccountSettings *self, __unsafe_unretained PBDataReader *reader);

@end

