/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Friday, November 1, 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from OTPairingMessage.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

#ifdef __cplusplus
#define OTAPPLICANTTOSPONSORROUND2M1_FUNCTION extern "C" __attribute__((visibility("hidden")))
#else
#define OTAPPLICANTTOSPONSORROUND2M1_FUNCTION extern __attribute__((visibility("hidden")))
#endif

__attribute__((visibility("hidden")))
@interface OTApplicantToSponsorRound2M1 : PBCodable <NSCopying>
{
    NSString *_peerID;
    NSData *_permanentInfo;
    NSData *_permanentInfoSig;
    NSData *_stableInfo;
    NSData *_stableInfoSig;
}


@property (nonatomic, readonly) BOOL hasPeerID;
@property (nonatomic, retain) NSString *peerID;

@property (nonatomic, readonly) BOOL hasPermanentInfo;
@property (nonatomic, retain) NSData *permanentInfo;

@property (nonatomic, readonly) BOOL hasPermanentInfoSig;
@property (nonatomic, retain) NSData *permanentInfoSig;

@property (nonatomic, readonly) BOOL hasStableInfo;
@property (nonatomic, retain) NSData *stableInfo;

@property (nonatomic, readonly) BOOL hasStableInfoSig;
@property (nonatomic, retain) NSData *stableInfoSig;

// Performs a shallow copy into other
- (void)copyTo:(OTApplicantToSponsorRound2M1 *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(OTApplicantToSponsorRound2M1 *)other;

OTAPPLICANTTOSPONSORROUND2M1_FUNCTION BOOL OTApplicantToSponsorRound2M1ReadFrom(__unsafe_unretained OTApplicantToSponsorRound2M1 *self, __unsafe_unretained PBDataReader *reader);

@end

