/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Sunday, September 11, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from OTAccountSettings.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

#ifdef __cplusplus
#define OTWALRUS_FUNCTION extern "C"
#else
#define OTWALRUS_FUNCTION extern
#endif

@interface OTWalrus : PBCodable <NSCopying>
{
    BOOL _enabled;
    struct {
        uint enabled:1;
    } _has;
}


@property (nonatomic) BOOL hasEnabled;
@property (nonatomic) BOOL enabled;

// Performs a shallow copy into other
- (void)copyTo:(OTWalrus *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(OTWalrus *)other;

OTWALRUS_FUNCTION BOOL OTWalrusReadFrom(__unsafe_unretained OTWalrus *self, __unsafe_unretained PBDataReader *reader);

@end

