include:
  - project: "GNOME/citemplates"
    file: "templates/default-rules.yml"
  - component: "gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master"
    inputs:
      meson-options: "-Ddocs=true -Dplugin-deviced=false -Dfeature-llm=true"
      lsan-options: "suppressions=${CI_PROJECT_DIR}/testsuite/lsan.supp"
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      dist-job-name: "build-gnomeos"
  - component: "gitlab.gnome.org/GNOME/citemplates/basic-deploy-docs@master"
