[package]
name = "papers-view-sys"
version = "0.0.1"
build = "build.rs"

[package.authors]
workspace = true

[package.edition]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[package.rust-version]
workspace = true

[package.metadata.system-deps.papers_view_4_0]
name = "papers-view-4.0"
version = "4"

[package.metadata.system-deps.papers_view_4_0.v42]
version = "42"

[package.metadata.system-deps.papers_view_4_0.v46]
version = "46"

[package.metadata.system-deps.papers_view_4_0.v48]
version = "48"

[package.metadata.system-deps.papers_view_4_0.v49]
version = "49"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
all-features = true

[lib]
name = "papers_view_sys"

[dependencies]
libc = "0.2"

[dependencies.papers-document-sys]
workspace = true

[dependencies.gio-sys]
workspace = true

[dependencies.glib-sys]
workspace = true

[dependencies.gobject-sys]
workspace = true

[dependencies.gdk-pixbuf-sys]
workspace = true

[dependencies.pango-sys]
workspace = true

[dependencies.cairo-sys-rs]
workspace = true

[dependencies.gtk-sys]
workspace = true

[dependencies.gdk-sys]
workspace = true

[build-dependencies]
system-deps = "7"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v42 = []
v46 = []
v48 = ["v46"]
v49 = ["v48"]
