[options]
library = "PapersView"
version = "4.0"
target_path = "."
min_cfg_version = "4.0"
work_mode = "sys"
disable_format = false
girs_directories = ["../../gir-files/", "../../pps-girs"]
single_version_file = true

external_libraries = [
    "Gio",
    "GLib",
    "GObject",
    "Cairo",
    "Gdk",
    "Gtk",
    "Pango",
    "PapersDocument"
]
