/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Monday, January 2, 2023.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#include "xotclInt.h"

/*
 * Remove macros that will interfere with the definitions below.
 */

/*
 * WARNING: The contents of this file is automatically generated by the
 * tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the generic/tcl.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

XotclIntStubs xotclIntStubs = {
    TCL_STUB_MAGIC,
    NULL,
};

static XotclStubHooks xotclStubHooks = {
    &xotclIntStubs
};

XotclStubs xotclStubs = {
    TCL_STUB_MAGIC,
    &xotclStubHooks,
    Xotcl_Init, /* 0 */
    NULL, /* 1 */
    XOTclIsClass, /* 2 */
    NULL, /* 3 */
    XOTclGetObject, /* 4 */
    XOTclGetClass, /* 5 */
    XOTclCreateObject, /* 6 */
    NULL, /* 7 */
    XOTclCreateClass, /* 8 */
    XOTclDeleteObject, /* 9 */
    XOTclDeleteClass, /* 10 */
    XOTclAddPMethod, /* 11 */
    XOTclAddIMethod, /* 12 */
    XOTclRemovePMethod, /* 13 */
    XOTclRemoveIMethod, /* 14 */
    XOTclOSetInstVar, /* 15 */
    XOTclOGetInstVar, /* 16 */
    XOTclInstVar, /* 17 */
    NULL, /* 18 */
    XOTclOSetInstVar2, /* 19 */
    XOTclOGetInstVar2, /* 20 */
    XOTclUnsetInstVar2, /* 21 */
    XOTcl_TraceObjCmd, /* 22 */
    XOTclErrMsg, /* 23 */
    XOTclVarErrMsg, /* 24 */
    XOTclErrInProc, /* 25 */
    XOTclObjErrArgCnt, /* 26 */
    XOTclErrBadVal_, /* 27 */
    XOTclObjErrType, /* 28 */
    XOTclStackDump, /* 29 */
    XOTclCallStackDump, /* 30 */
    XOTclDeprecatedMsg, /* 31 */
    XOTclSetObjClientData, /* 32 */
    XOTclGetObjClientData, /* 33 */
    XOTclSetClassClientData, /* 34 */
    XOTclGetClassClientData, /* 35 */
    XOTclRequireObjNamespace, /* 36 */
    XOTclErrBadVal, /* 37 */
    XOTclNextObjCmd, /* 38 */
    XOTclCallMethodWithArgs, /* 39 */
};

/* !END!: Do not edit above this line. */
