/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Tuesday, November 19, 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#define __XML_GLOBALS_H

#include <libxml/parser.h>

/* Typedefs from <libxml/globals.h>. */
typedef void (*xmlRegisterNodeFunc) (xmlNodePtr node);
typedef void (*xmlDeregisterNodeFunc) (xmlNodePtr node);
typedef xmlParserInputBufferPtr (*xmlParserInputBufferCreateFilenameFunc) (const char *URI, xmlCharEncoding enc);
typedef xmlOutputBufferPtr (*xmlOutputBufferCreateFilenameFunc) (const char *URI, xmlCharEncodingHandlerPtr encoder, int compression);

#ifdef __cplusplus
extern "C" {
#endif

#ifdef LIBXML_DOCB_ENABLED
XMLPUBVAR xmlSAXHandlerV1 docbDefaultSAXHandler;
#endif

#ifdef LIBXML_HTML_ENABLED
XMLPUBVAR xmlSAXHandlerV1 htmlDefaultSAXHandler;
#endif

XMLPUBVAR xmlError xmlLastError;

/*
 * Everything starting from the line below is
 * Automatically generated by build_glob.py.
 * Do not modify the previous line.
 */

XMLPUBVAR int oldXMLWDcompatibility;

XMLPUBVAR xmlBufferAllocationScheme xmlBufferAllocScheme;

XMLPUBVAR int xmlDefaultBufferSize;

XMLPUBVAR xmlSAXHandlerV1 xmlDefaultSAXHandler;

XMLPUBVAR xmlSAXLocator xmlDefaultSAXLocator;

XMLPUBVAR int xmlDoValidityCheckingDefaultValue;

XMLPUBVAR xmlGenericErrorFunc xmlGenericError;

XMLPUBVAR xmlStructuredErrorFunc xmlStructuredError;

XMLPUBVAR void * xmlGenericErrorContext;

XMLPUBVAR void * xmlStructuredErrorContext;

XMLPUBVAR int xmlGetWarningsDefaultValue;

XMLPUBVAR int xmlIndentTreeOutput;

XMLPUBVAR const char * xmlTreeIndentString;

XMLPUBVAR int xmlKeepBlanksDefaultValue;

XMLPUBVAR int xmlLineNumbersDefaultValue;

XMLPUBVAR int xmlLoadExtDtdDefaultValue;

XMLPUBVAR int xmlParserDebugEntities;

XMLPUBVAR const char * xmlParserVersion;

XMLPUBVAR int xmlPedanticParserDefaultValue;

XMLPUBVAR int xmlSaveNoEmptyTags;

XMLPUBVAR int xmlSubstituteEntitiesDefaultValue;

XMLPUBVAR xmlRegisterNodeFunc xmlRegisterNodeDefaultValue;

XMLPUBVAR xmlDeregisterNodeFunc xmlDeregisterNodeDefaultValue;

XMLPUBVAR xmlParserInputBufferCreateFilenameFunc xmlParserInputBufferCreateFilenameValue;

XMLPUBVAR xmlOutputBufferCreateFilenameFunc xmlOutputBufferCreateFilenameValue;

#ifdef __cplusplus
}
#endif
