include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "flatpak"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

variables:
  FLATPAK_MODULE: "showtime"
  TARBALL_ARTIFACT_PATH: ".flatpak-builder/build/${FLATPAK_MODULE}/_flatpak_build/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

flatpak:
  extends: ".flatpak"
  variables:
    MANIFEST_PATH: "build-aux/flatpak/org.gnome.Showtime.Devel.json"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.Showtime.Devel"
    BUNDLE: "org.gnome.Showtime.Devel.flatpak"

nightly:
  extends: ".publish_nightly"
  dependencies: ["flatpak"]
  needs: ["flatpak"]
