services:
  gnome-shell-integration-website-vscode:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VERSION: '3.10'
    image: gnome-shell-integration-website-vscode
    volumes:
      - "../:/workspace:cached"
    networks:
      - gnome-shell-integration-website

networks:
  gnome-shell-integration-website:
