/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Tuesday, January 4, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from OTCDPRecoveryInformation.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

#ifdef __cplusplus
#define OTCDPRECOVERYINFORMATION_FUNCTION extern "C"
#else
#define OTCDPRECOVERYINFORMATION_FUNCTION extern
#endif

@interface OTCDPRecoveryInformation : PBCodable <NSCopying>
{
    NSString *_recoveryKey;
    NSString *_recoverySecret;
    BOOL _containsIcdpData;
    BOOL _nonViableRepair;
    BOOL _silentRecoveryAttempt;
    BOOL _useCachedSecret;
    BOOL _usePreviouslyCachedRecoveryKey;
    BOOL _usesMultipleIcsc;
    struct {
        uint containsIcdpData:1;
        uint nonViableRepair:1;
        uint silentRecoveryAttempt:1;
        uint useCachedSecret:1;
        uint usePreviouslyCachedRecoveryKey:1;
        uint usesMultipleIcsc:1;
    } _has;
}


@property (nonatomic, readonly) BOOL hasRecoverySecret;
@property (nonatomic, retain) NSString *recoverySecret;

@property (nonatomic) BOOL hasUseCachedSecret;
@property (nonatomic) BOOL useCachedSecret;

@property (nonatomic, readonly) BOOL hasRecoveryKey;
@property (nonatomic, retain) NSString *recoveryKey;

@property (nonatomic) BOOL hasUsePreviouslyCachedRecoveryKey;
@property (nonatomic) BOOL usePreviouslyCachedRecoveryKey;

@property (nonatomic) BOOL hasSilentRecoveryAttempt;
@property (nonatomic) BOOL silentRecoveryAttempt;

@property (nonatomic) BOOL hasContainsIcdpData;
@property (nonatomic) BOOL containsIcdpData;

@property (nonatomic) BOOL hasUsesMultipleIcsc;
@property (nonatomic) BOOL usesMultipleIcsc;

@property (nonatomic) BOOL hasNonViableRepair;
@property (nonatomic) BOOL nonViableRepair;

// Performs a shallow copy into other
- (void)copyTo:(OTCDPRecoveryInformation *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(OTCDPRecoveryInformation *)other;

OTCDPRECOVERYINFORMATION_FUNCTION BOOL OTCDPRecoveryInformationReadFrom(__unsafe_unretained OTCDPRecoveryInformation *self, __unsafe_unretained PBDataReader *reader);

@end

