.TH papers 1 2025\-04\-22 GNOME
.SH NAME
\fBpapers\fP \- GNOME document viewer

The Papers Document Viewer application for the GNOME desktop environment

.SH SYNTAX
.B papers
.RI [--help]
.RI [--page-label=PAGE\ |
.RI --page-index=NUMBER\ |
.RI --named-dest=DEST]
.RI [--fullscreen]
.RI [--presentation]
.RI [filename(s)...]
.SH DESCRIPTION

Papers is a document viewer capable of displaying multiple and single
page document formats like PDF and DjVu.  For more general
information about Papers please visit our website at
https://apps.gnome.org/Papers/

.LP
.SH OPTIONS

.TP
\fB\-?, \-h, \-\-help\fR
Prints the command line options.
.TP
\fB\-p, \-\-page\-label=PAGE\fR
Open the document on the page with the specified page label (or page number).
.TP
\fB\-i, \-\-page\-index=NUMBER\fR
Open the document on the page with the specified page index (this is the exact page number, not a page label).
.TP
\fB\-n, \-\-named\-dest=DEST\fR
Open the document on the specified named destination.
.TP
\fB\-f, \-\-fullscreen\fR
Run papers in fullscreen mode.
.TP
\fB\-s, \-\-presentation\fR
Run papers in presentation mode.
.TP
\fBfilename(s)...\fR
Specifies the file to open when Papers starts. If this is not
specified, Papers will open a blank window. Multiple files can be loaded
if they are separated by spaces.  Papers also supports handling of
remote files.  For example, you can pass the location on the web or load
a file from a FTP server, like "ftp://adobe.com/sample.pdf".

.SH BUGS
If you find a bug, please report it at https://gitlab.gnome.org/GNOME/papers/issues.
