# SPDX-FileCopyrightText: 2025 Florian Müllner <fmuellner@gnome.org>
# SPDX-License-Identifier: LGPL-2.1-or-later

include:
  - project: GNOME/citemplates
    file: templates/default-rules.yml
  - component: gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master
    inputs:
      meson-sourcedir: test-project
      run-tests: no # run tests ourselves to not disable x11 support
      asan: disabled
      before-script: mkdir -m 1777 /tmp/.X11-unix
  - project: Infrastructure/freedesktop-ci-templates
    file: templates/ci-fairy.yml

stages:
 - review
 - build

.skip-git-clone:
  variables:
    GIT_STRATEGY: none

.only-merge-requests:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^$/'
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      when: on_success

build-gnomeos:
  extends: ".build-gnomeos common"
  script:
    - !reference [".build-gnomeos common", script]
    - dbus-run-session
        -- mutter --headless --wayland --virtual-monitor 1024x768
          -- meson test -C ${_BUILDDIR} --print-errorlogs --no-stdsplit --no-rebuild --setup plain

check-merge-request:
  extends:
    - .fdo.ci-fairy
    - .skip-git-clone
  stage: review
  script:
    ci-fairy check-merge-request --require-allow-collaboration --junit-xml=check-merge-request-report.xml
  artifacts:
    expire_in: 1 week
    paths:
      - check-merge-request-report.xml
    reports:
      junit: check-merge-request-report.xml
  rules:
    - !reference [.only-merge-requests, rules]

check-commit-log:
  extends:
    - .fdo.ci-fairy
  stage: review
  script:
    ci-fairy check-commits --junit-xml=commit-messages-report.xml
  artifacts:
    expire_in: 1 week
    paths:
      - commit-messages-report.xml
    reports:
      junit: commit-messages-report.xml
  rules:
    - !reference [.only-merge-requests, rules]

check-reuse:
  stage: review
  image:
    name: fsfe/reuse:latest
    entrypoint: ['']
  script:
    - reuse lint
