[package]
name = "papers-document"
version = "0.1.0"
license = "MIT"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true
# For build.rs scripts
rustc-args = ["--cfg", "docsrs"]
# For rustdoc
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["v49"]
v42 = ["papers-document-sys/v42"]
v47 = ["papers-document-sys/v47", "v42"]
v48 = ["papers-document-sys/v48", "v47"]
v49 = ["papers-document-sys/v49", "v48"]

[dependencies]
papers-document-sys.workspace = true
libc = "0.2"
bitflags = "2.2"
glib.workspace = true
gio.workspace = true
gdk-pixbuf.workspace = true
gtk.workspace = true
gdk.workspace = true
cairo-rs.workspace = true
pango.workspace = true
