include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Screenshot.json'
    FLATPAK_MODULE: 'gnome-screenshot'
    RUNTIME_REPO: 'https://sdk.gnome.org/gnome-nightly.flatpakrepo'
    APP_ID: 'org.gnome.Screenshot'
    BUNDLE: 'org.gnome.Screenshot.Devel.flatpak'

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak']
    needs: ['flatpak']
