/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Friday, October 14, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from C2Metric.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

@class SECC2MPError;

#ifdef __cplusplus
#define SECC2MPERROR_FUNCTION extern "C" __attribute__((visibility("hidden")))
#else
#define SECC2MPERROR_FUNCTION extern __attribute__((visibility("hidden")))
#endif

__attribute__((visibility("hidden")))
@interface SECC2MPError : PBCodable <NSCopying>
{
    int64_t _errorCode;
    NSString *_errorDescription;
    NSString *_errorDomain;
    SECC2MPError *_underlyingError;
    struct {
        uint errorCode:1;
    } _has;
}


@property (nonatomic, readonly) BOOL hasErrorDomain;
@property (nonatomic, retain) NSString *errorDomain;

@property (nonatomic) BOOL hasErrorCode;
@property (nonatomic) int64_t errorCode;

@property (nonatomic, readonly) BOOL hasErrorDescription;
@property (nonatomic, retain) NSString *errorDescription;

@property (nonatomic, readonly) BOOL hasUnderlyingError;
@property (nonatomic, retain) SECC2MPError *underlyingError;

// Performs a shallow copy into other
- (void)copyTo:(SECC2MPError *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(SECC2MPError *)other;

SECC2MPERROR_FUNCTION BOOL SECC2MPErrorReadFrom(__unsafe_unretained SECC2MPError *self, __unsafe_unretained PBDataReader *reader);

@end

