/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Monday, March 21, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from C2Metric.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

#ifdef __cplusplus
#define SECC2MPCLOUDKITOPERATIONINFO_FUNCTION extern "C" __attribute__((visibility("hidden")))
#else
#define SECC2MPCLOUDKITOPERATIONINFO_FUNCTION extern __attribute__((visibility("hidden")))
#endif

__attribute__((visibility("hidden")))
@interface SECC2MPCloudKitOperationInfo : PBCodable <NSCopying>
{
    uint32_t _operationGroupIndex;
    NSString *_operationId;
    NSString *_operationType;
    BOOL _operationTriggered;
    struct {
        uint operationGroupIndex:1;
        uint operationTriggered:1;
    } _has;
}


@property (nonatomic, readonly) BOOL hasOperationId;
@property (nonatomic, retain) NSString *operationId;

@property (nonatomic, readonly) BOOL hasOperationType;
@property (nonatomic, retain) NSString *operationType;

@property (nonatomic) BOOL hasOperationTriggered;
@property (nonatomic) BOOL operationTriggered;

@property (nonatomic) BOOL hasOperationGroupIndex;
/** Index of associated Metric.CloudKitInfo.operation_group */
@property (nonatomic) uint32_t operationGroupIndex;

// Performs a shallow copy into other
- (void)copyTo:(SECC2MPCloudKitOperationInfo *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(SECC2MPCloudKitOperationInfo *)other;

SECC2MPCLOUDKITOPERATIONINFO_FUNCTION BOOL SECC2MPCloudKitOperationInfoReadFrom(__unsafe_unretained SECC2MPCloudKitOperationInfo *self, __unsafe_unretained PBDataReader *reader);

@end

