/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Wednesday, March 12, 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#ifndef _TCLDOMDECLS
#define _TCLDOMDECLS

/*
 * WARNING: The contents of this file is automatically generated by the
 * genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the tcldom.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/*
 * Exported function declarations:
 */

/* Slot 0 is reserved */
/* Slot 1 is reserved */
/* 2 */
EXTERN int		TclDOM_Register _ANSI_ARGS_((Tcl_Interp * interp, 
				TclDOM_Implementation * impl));

typedef struct TcldomStubs {
    int magic;
    struct TcldomStubHooks *hooks;

    void *reserved0;
    void *reserved1;
    int (*tclDOM_Register) _ANSI_ARGS_((Tcl_Interp * interp, TclDOM_Implementation * impl)); /* 2 */
} TcldomStubs;

#ifdef __cplusplus
extern "C" {
#endif
extern TcldomStubs *tcldomStubsPtr;
#ifdef __cplusplus
}
#endif

#if defined(USE_TCLDOM_STUBS) && !defined(USE_TCLDOM_STUB_PROCS)

/*
 * Inline function declarations:
 */

/* Slot 0 is reserved */
/* Slot 1 is reserved */
#ifndef TclDOM_Register
#define TclDOM_Register \
	(tcldomStubsPtr->tclDOM_Register) /* 2 */
#endif

#endif /* defined(USE_TCLDOM_STUBS) && !defined(USE_TCLDOM_STUB_PROCS) */

/* !END!: Do not edit above this line. */

#endif /* _TCLXMLDECLS */

