/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Saturday, August 23, 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
//
// This file is automatically generated. DO NOT EDIT!
// To add options, see genSCTestOptions.c
//
#import <TargetConditionals.h>
#import "SCTestOptions.h"

const NSString * const kSCTestGlobalOptionCPU                            = @"cpu_Str";
const NSString * const kSCTestGlobalOptionHelp                           = @"help_Str";
const NSString * const kSCTestGlobalOptionTime                           = @"time_Str";
const NSString * const kSCTestGlobalOptionVerbose                        = @"verbose_Str";
const NSString * const kSCTestGlobalOptionWait                           = @"wait_Str";
const NSString * const kSCTestUnitTestCommand                            = @"command_Str";
const NSString * const kSCTestUnitTestListTests                          = @"list_tests_Str";
const NSString * const kSCTestUnitTestTestMethod                         = @"test_method_Str";
const NSString * const kSCTestUnitTestTestMethodList                     = @"test_method_list_Str";
const NSString * const kSCTestDynamicStoreOptionDNS                      = @"dns_Str";
const NSString * const kSCTestDynamicStoreOptionIPv4                     = @"ipv4_Str";
const NSString * const kSCTestDynamicStoreOptionIPv6                     = @"ipv6_Str";
const NSString * const kSCTestDynamicStoreOptionProxies                  = @"proxies_Str";
#if !TARGET_OS_BRIDGE
const NSString * const kSCTestPreferencesServiceList                     = @"service_list_Str";
const NSString * const kSCTestPreferencesServiceOrder                    = @"service_order_Str";
const NSString * const kSCTestConfigAgentDNSDomains                      = @"dns_domain_Str";
const NSString * const kSCTestConfigAgentDNSServers                      = @"dns_servers_Str";
const NSString * const kSCTestConfigAgentRemoveDNS                       = @"remove_dns_Str";
const NSString * const kSCTestConfigAgentFTPProxy                        = @"ftp_proxy_Str";
const NSString * const kSCTestConfigAgentGopherProxy                     = @"gopher_proxy_Str";
const NSString * const kSCTestConfigAgentHTTPProxy                       = @"http_proxy_Str";
const NSString * const kSCTestConfigAgentHTTPSProxy                      = @"https_proxy_Str";
const NSString * const kSCTestConfigAgentProxyMatchDomain                = @"proxy_match_domain_Str";
const NSString * const kSCTestConfigAgentRemoveProxy                     = @"remove_proxy_Str";
const NSString * const kSCTestConfigAgentSOCKSProxy                      = @"socks_proxy_Str";
const NSString * const kSCTestReachabilityAddress                        = @"address_Str";
const NSString * const kSCTestReachabilityHost                           = @"host_Str";
const NSString * const kSCTestReachabilityInterface                      = @"interface_Str";
const NSString * const kSCTestReachabilityWatch                          = @"watch_Str";
const NSString * const kSCTestInterfaceRankAssertion                     = @"interface_rank_Str";
const NSString * const kSCTestServiceRankAssertion                       = @"service_rank_Str";
#endif // !TARGET_OS_BRIDGE
