[package]
name = "papers-thumbnailer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
papers-document.workspace = true
gio.workspace = true
glib.workspace = true
env_logger.workspace = true
log.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
