/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Sunday, February 9, 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#ifndef HEADER_CCA4758_ERR_H
#define HEADER_CCA4758_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_CCA4758_strings(void);
static void ERR_unload_CCA4758_strings(void);
static void ERR_CCA4758_error(int function, int reason, char *file, int line);
#define CCA4758err(f,r) ERR_CCA4758_error((f),(r),__FILE__,__LINE__)

/* Error codes for the CCA4758 functions. */

/* Function codes. */
#define CCA4758_F_CCA_RSA_SIGN				 105
#define CCA4758_F_CCA_RSA_VERIFY			 106
#define CCA4758_F_IBM_4758_CCA_CTRL			 100
#define CCA4758_F_IBM_4758_CCA_FINISH			 101
#define CCA4758_F_IBM_4758_CCA_INIT			 102
#define CCA4758_F_IBM_4758_LOAD_PRIVKEY			 103
#define CCA4758_F_IBM_4758_LOAD_PUBKEY			 104

/* Reason codes. */
#define CCA4758_R_ALREADY_LOADED			 100
#define CCA4758_R_ASN1_OID_UNKNOWN_FOR_MD		 101
#define CCA4758_R_COMMAND_NOT_IMPLEMENTED		 102
#define CCA4758_R_DSO_FAILURE				 103
#define CCA4758_R_FAILED_LOADING_PRIVATE_KEY		 104
#define CCA4758_R_FAILED_LOADING_PUBLIC_KEY		 105
#define CCA4758_R_NOT_LOADED				 106
#define CCA4758_R_SIZE_TOO_LARGE_OR_TOO_SMALL		 107
#define CCA4758_R_UNIT_FAILURE				 108
#define CCA4758_R_UNKNOWN_ALGORITHM_TYPE		 109

#ifdef  __cplusplus
}
#endif
#endif
