/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Monday, August 26, 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#ifndef HEADER_AEPHK_ERR_H
#define HEADER_AEPHK_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_AEPHK_strings(void);
static void ERR_unload_AEPHK_strings(void);
static void ERR_AEPHK_error(int function, int reason, char *file, int line);
#define AEPHKerr(f,r) ERR_AEPHK_error((f),(r),__FILE__,__LINE__)

/* Error codes for the AEPHK functions. */

/* Function codes. */
#define AEPHK_F_AEP_CTRL				 100
#define AEPHK_F_AEP_FINISH				 101
#define AEPHK_F_AEP_GET_CONNECTION			 102
#define AEPHK_F_AEP_INIT				 103
#define AEPHK_F_AEP_MOD_EXP				 104
#define AEPHK_F_AEP_MOD_EXP_CRT				 105
#define AEPHK_F_AEP_RAND				 106
#define AEPHK_F_AEP_RSA_MOD_EXP				 107

/* Reason codes. */
#define AEPHK_R_ALREADY_LOADED				 100
#define AEPHK_R_CLOSE_HANDLES_FAILED			 101
#define AEPHK_R_CONNECTIONS_IN_USE			 102
#define AEPHK_R_CTRL_COMMAND_NOT_IMPLEMENTED		 103
#define AEPHK_R_FINALIZE_FAILED				 104
#define AEPHK_R_GET_HANDLE_FAILED			 105
#define AEPHK_R_GET_RANDOM_FAILED			 106
#define AEPHK_R_INIT_FAILURE				 107
#define AEPHK_R_MISSING_KEY_COMPONENTS			 108
#define AEPHK_R_MOD_EXP_CRT_FAILED			 109
#define AEPHK_R_MOD_EXP_FAILED				 110
#define AEPHK_R_NOT_LOADED				 111
#define AEPHK_R_OK					 112
#define AEPHK_R_RETURN_CONNECTION_FAILED		 113
#define AEPHK_R_SETBNCALLBACK_FAILURE			 114
#define AEPHK_R_SIZE_TOO_LARGE_OR_TOO_SMALL		 116
#define AEPHK_R_UNIT_FAILURE				 115

#ifdef  __cplusplus
}
#endif
#endif
