/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Wednesday, July 31, 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#ifndef HEADER_ATALLA_ERR_H
#define HEADER_ATALLA_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_ATALLA_strings(void);
static void ERR_unload_ATALLA_strings(void);
static void ERR_ATALLA_error(int function, int reason, char *file, int line);
#define ATALLAerr(f,r) ERR_ATALLA_error((f),(r),__FILE__,__LINE__)

/* Error codes for the ATALLA functions. */

/* Function codes. */
#define ATALLA_F_ATALLA_CTRL				 100
#define ATALLA_F_ATALLA_FINISH				 101
#define ATALLA_F_ATALLA_INIT				 102
#define ATALLA_F_ATALLA_MOD_EXP				 103
#define ATALLA_F_ATALLA_RSA_MOD_EXP			 104

/* Reason codes. */
#define ATALLA_R_ALREADY_LOADED				 100
#define ATALLA_R_BN_CTX_FULL				 101
#define ATALLA_R_BN_EXPAND_FAIL				 102
#define ATALLA_R_CTRL_COMMAND_NOT_IMPLEMENTED		 103
#define ATALLA_R_MISSING_KEY_COMPONENTS			 104
#define ATALLA_R_NOT_LOADED				 105
#define ATALLA_R_REQUEST_FAILED				 106
#define ATALLA_R_UNIT_FAILURE				 107

#ifdef  __cplusplus
}
#endif
#endif
