/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Sunday, November 5, 2023.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#ifndef HEADER_HWCRHK_ERR_H
#define HEADER_HWCRHK_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_HWCRHK_strings(void);
static void ERR_unload_HWCRHK_strings(void);
static void ERR_HWCRHK_error(int function, int reason, char *file, int line);
#define HWCRHKerr(f,r) ERR_HWCRHK_error((f),(r),__FILE__,__LINE__)

/* Error codes for the HWCRHK functions. */

/* Function codes. */
#define HWCRHK_F_HWCRHK_CTRL				 100
#define HWCRHK_F_HWCRHK_FINISH				 101
#define HWCRHK_F_HWCRHK_GET_PASS			 102
#define HWCRHK_F_HWCRHK_INIT				 103
#define HWCRHK_F_HWCRHK_INSERT_CARD			 104
#define HWCRHK_F_HWCRHK_LOAD_PRIVKEY			 105
#define HWCRHK_F_HWCRHK_LOAD_PUBKEY			 106
#define HWCRHK_F_HWCRHK_MOD_EXP				 107
#define HWCRHK_F_HWCRHK_RAND_BYTES			 108
#define HWCRHK_F_HWCRHK_RSA_MOD_EXP			 109

/* Reason codes. */
#define HWCRHK_R_ALREADY_LOADED				 100
#define HWCRHK_R_BIO_WAS_FREED				 101
#define HWCRHK_R_CHIL_ERROR				 102
#define HWCRHK_R_CTRL_COMMAND_NOT_IMPLEMENTED		 103
#define HWCRHK_R_DSO_FAILURE				 104
#define HWCRHK_R_MISSING_KEY_COMPONENTS			 105
#define HWCRHK_R_NOT_INITIALISED			 106
#define HWCRHK_R_NOT_LOADED				 107
#define HWCRHK_R_NO_CALLBACK				 108
#define HWCRHK_R_NO_KEY					 109
#define HWCRHK_R_PRIVATE_KEY_ALGORITHMS_DISABLED	 110
#define HWCRHK_R_REQUEST_FAILED				 111
#define HWCRHK_R_REQUEST_FALLBACK			 112
#define HWCRHK_R_UNIT_FAILURE				 113

#ifdef  __cplusplus
}
#endif
#endif
