/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Wednesday, July 27, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#ifndef HEADER_GMP_ERR_H
#define HEADER_GMP_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_GMP_strings(void);
static void ERR_unload_GMP_strings(void);
static void ERR_GMP_error(int function, int reason, char *file, int line);
#define GMPerr(f,r) ERR_GMP_error((f),(r),__FILE__,__LINE__)

/* Error codes for the GMP functions. */

/* Function codes. */
#define GMP_F_E_GMP_CTRL				 100
#define GMP_F_E_GMP_RSA_MOD_EXP				 101

/* Reason codes. */
#define GMP_R_CTRL_COMMAND_NOT_IMPLEMENTED		 100
#define GMP_R_KEY_CONTEXT_ERROR				 101
#define GMP_R_MISSING_KEY_COMPONENTS			 102

#ifdef  __cplusplus
}
#endif
#endif
