/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Thursday, September 15, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#ifndef HEADER_UBSEC_ERR_H
#define HEADER_UBSEC_ERR_H

#ifdef  __cplusplus
extern "C" {
#endif

/* BEGIN ERROR CODES */
/* The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */
static void ERR_load_UBSEC_strings(void);
static void ERR_unload_UBSEC_strings(void);
static void ERR_UBSEC_error(int function, int reason, char *file, int line);
#define UBSECerr(f,r) ERR_UBSEC_error((f),(r),__FILE__,__LINE__)

/* Error codes for the UBSEC functions. */

/* Function codes. */
#define UBSEC_F_UBSEC_CTRL				 100
#define UBSEC_F_UBSEC_DH_COMPUTE_KEY			 101
#define UBSEC_F_UBSEC_DH_GENERATE_KEY			 111
#define UBSEC_F_UBSEC_DSA_DO_SIGN			 102
#define UBSEC_F_UBSEC_DSA_VERIFY			 103
#define UBSEC_F_UBSEC_FINISH				 104
#define UBSEC_F_UBSEC_INIT				 105
#define UBSEC_F_UBSEC_MOD_EXP				 106
#define UBSEC_F_UBSEC_MOD_EXP_CRT			 110
#define UBSEC_F_UBSEC_RAND_BYTES			 107
#define UBSEC_F_UBSEC_RSA_MOD_EXP			 108
#define UBSEC_F_UBSEC_RSA_MOD_EXP_CRT			 109

/* Reason codes. */
#define UBSEC_R_ALREADY_LOADED				 100
#define UBSEC_R_BN_EXPAND_FAIL				 101
#define UBSEC_R_CTRL_COMMAND_NOT_IMPLEMENTED		 102
#define UBSEC_R_DSO_FAILURE				 103
#define UBSEC_R_MISSING_KEY_COMPONENTS			 104
#define UBSEC_R_NOT_LOADED				 105
#define UBSEC_R_REQUEST_FAILED				 106
#define UBSEC_R_SIZE_TOO_LARGE_OR_TOO_SMALL		 107
#define UBSEC_R_UNIT_FAILURE				 108

#ifdef  __cplusplus
}
#endif
#endif
