/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Thursday, November 28, 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sm_inter.h"
#ifndef lint
/*static char sccsid[] = "from: @(#)sm_inter.x 1.7 87/06/24 Copyr 1987 Sun Micro";*/
/*static char sccsid[] = "from: @(#)sm_inter.x	2.2 88/08/01 4.0 RPCSRC";*/
__unused static char rcsid[] = "$Id: sm_inter_xdr.c,v 1.3 2006/02/07 06:22:32 lindak Exp $";
#endif /* not lint */

bool_t
xdr_sm_name(XDR *xdrs, sm_name *objp)
{
	if (!xdr_string(xdrs, &objp->mon_name, SM_MAXSTRLEN)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_my_id(XDR *xdrs, my_id *objp)
{
	if (!xdr_string(xdrs, &objp->my_name, SM_MAXSTRLEN)) {
		return FALSE;
	}
	if (!xdr_int(xdrs, &objp->my_prog)) {
		return FALSE;
	}
	if (!xdr_int(xdrs, &objp->my_vers)) {
		return FALSE;
	}
	if (!xdr_int(xdrs, &objp->my_proc)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_mon_id(XDR *xdrs, mon_id *objp)
{
	if (!xdr_string(xdrs, &objp->mon_name, SM_MAXSTRLEN)) {
		return FALSE;
	}
	if (!xdr_my_id(xdrs, &objp->my_id)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_mon(XDR *xdrs, mon *objp)
{
	if (!xdr_mon_id(xdrs, &objp->mon_id)) {
		return FALSE;
	}
	if (!xdr_opaque(xdrs, (uint8_t *) objp->priv, 16)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_stat_chge(XDR *xdrs, stat_chge *objp)
{
	if (!xdr_string(xdrs, &objp->mon_name, SM_MAXSTRLEN)) {
		return FALSE;
	}
	if (!xdr_int(xdrs, &objp->state)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_sm_stat(XDR *xdrs, sm_stat *objp)
{
	if (!xdr_int(xdrs, &objp->state)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_sm_res(XDR *xdrs, sm_res *objp)
{
	if (!xdr_enum(xdrs, (enum_t *)objp)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_sm_stat_res(XDR *xdrs, sm_stat_res *objp)
{
	if (!xdr_sm_res(xdrs, &objp->res_stat)) {
		return FALSE;
	}
	if (!xdr_int(xdrs, &objp->state)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_sm_status(XDR *xdrs, sm_status *objp)
{
	if (!xdr_string(xdrs, &objp->mon_name, SM_MAXSTRLEN)) {
		return FALSE;
	}
	if (!xdr_int(xdrs, &objp->state)) {
		return FALSE;
	}
	if (!xdr_opaque(xdrs, (uint8_t *) objp->priv, 16)) {
		return FALSE;
	}
	return TRUE;
}
