/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Wednesday, February 22, 2023.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#include "transformInt.h"

/*
 * WARNING: The contents of this file is automatically generated by the
 * tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the generic/trf.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

TrfIntStubs trfIntStubs = {
    TCL_STUB_MAGIC,
    NULL,
};

static TrfStubHooks trfStubHooks = {
    &trfIntStubs
};

TrfStubs trfStubs = {
    TCL_STUB_MAGIC,
    &trfStubHooks,
    Trf_IsInitialized, /* 0 */
    Trf_Register, /* 1 */
    Trf_ConverterOptions, /* 2 */
    Trf_LoadLibrary, /* 3 */
    Trf_LoadFailed, /* 4 */
    Trf_RegisterMessageDigest, /* 5 */
    Trf_XorBuffer, /* 6 */
    Trf_ShiftRegister, /* 7 */
    Trf_FlipRegisterLong, /* 8 */
    Trf_FlipRegisterShort, /* 9 */
};

/* !END!: Do not edit above this line. */
