/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Tuesday, May 9, 2023.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
#ifndef __OS_DEBUG_LOG_H__
#define __OS_DEBUG_LOG_H__

#include <Availability.h>
#include <TargetConditionals.h>

#include <os/base_private.h>
#include <stdarg.h>

__OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_6_0)
OS_FORMAT_PRINTF(1, 2) OS_COLD
extern void
_os_debug_log(const char *msg, ...);

/* The os_debug_log macros insert spaces before the message. If logging to a file,
 * the spaces will be replaced by a timestamp. If logging to syslog, they will
 * be skipped (syslog knows what time it is). There are 20 spaces because the
 * timestamp is printed as %16llu + 4 spaces before the next column.
 * 10^16 ns = 3.8 months. Don't run your process in _debug for that long. This
 * isn't syslog.
 */
#define _OS_DEBUG_LOG_PREFIX "                    "

#define os_debug_log(tag, fmt, ...) __extension__({\
	_os_debug_log(_OS_DEBUG_LOG_PREFIX "%s: " fmt, tag, ## __VA_ARGS__); \
})

#define os_debug_log_ctx(tag, ctx, fmt, ...) __extension__({\
	_os_debug_log(_OS_DEBUG_LOG_PREFIX "[%p]  %s: " fmt, ctx, tag, ## __VA_ARGS__); \
})

/* This is useful for clients who wish for the messages generated by os_debug_log()
 * or os_assumes() failures to go somewhere other than (or in addition to) the
 * system log, for example launchd or syslogd itself. If you don't wish for the
 * message to be logged to the system log, then return true (to indicate that
 * the message has been handled). If you want the default behavior, return
 * false. Please use this macro, rather than directly declaring a function,
 * since the declaration magic may change in the future.
 */
#define os_debug_log_redirect(func) \
	__attribute__((__used__)) \
	__attribute__((__cold__)) \
	__attribute__((__visibility__("default"))) \
	bool _os_debug_log_redirect_func(const char *msg) { \
		return func(msg); \
	}

# pragma mark -
# pragma mark Private To Libc

// str must be modifiable (non-const)!
__OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_6_0)
OS_COLD
extern void
_os_debug_log_error_str(char *str);

#endif /* __OS_DEBUG_LOG_H__ */
