/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Thursday, May 11, 2023.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
/*
 * This file was auto-generated by ./genoptionfiles -dhcptype, do not edit!
 */
#ifndef _S_DHCP_TYPE
#define _S_DHCP_TYPE

enum {
    dhcptype_first_e    	 = 0,
    dhcptype_none_e     	 = dhcptype_first_e,
    dhcptype_opaque_e   	 = 1,
    dhcptype_bool_e     	 = 2,
    dhcptype_uint8_e    	 = 3,
    dhcptype_uint16_e   	 = 4,
    dhcptype_uint32_e   	 = 5,
    dhcptype_int32_e    	 = 6,
    dhcptype_uint8_mult_e	 = 7,
    dhcptype_uint16_mult_e	 = 8,
    dhcptype_string_e   	 = 9,
    dhcptype_ip_e       	 = 10,
    dhcptype_ip_mult_e  	 = 11,
    dhcptype_ip_pairs_e 	 = 12,
    dhcptype_dns_namelist_e	 = 13,
    dhcptype_classless_route_e	 = 14,
    dhcptype_last_e     	 = dhcptype_classless_route_e,
};

typedef uint32_t dhcptype_t;

typedef struct {
    dhcptype_t	type;
    const char *	name;
} dhcptag_info_t;

typedef struct {
    int		size;  /* in bytes */
    int		multiple_of; /* type of element */
    const char * name;
    int		string_list;
} dhcptype_info_t;

#endif /* _S_DHCP_TYPE */
