"""empty message

Revision ID: 10f0fba3e65f
Revises: 4cea4a5fe287
Create Date: 2025-03-18 18:25:40.703049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f0fba3e65f'
down_revision = '4cea4a5fe287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_date_created'), ['date_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reported'), ['reported'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reported'))
        batch_op.drop_index(batch_op.f('ix_reviews_date_created'))

    # ### end Alembic commands ###
