"""Initial migration.

Revision ID: c856bd600df0
Revises: 
Create Date: 2022-04-25 09:02:57.555232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c856bd600df0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('datestr', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=128), nullable=False),
    sa.Column('fetch_cnt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datestr', 'app_id'),
    mysql_character_set='utf8mb4'
    )
    op.create_index('datestr', 'analytics', ['datestr', 'app_id'], unique=True)
    op.create_table('components',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('component_id_parent', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Text(), nullable=True),
    sa.Column('fetch_cnt', sa.Integer(), nullable=True),
    sa.Column('review_cnt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id_parent'], ['components.component_id'], ),
    sa.PrimaryKeyConstraint('component_id'),
    sa.UniqueConstraint('component_id'),
    mysql_character_set='utf8mb4'
    )
    op.create_table('taboos',
    sa.Column('taboo_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('taboo_id'),
    sa.UniqueConstraint('taboo_id'),
    mysql_character_set='utf8mb4'
    )
    op.create_index(op.f('ix_taboos_locale'), 'taboos', ['locale'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_hash', sa.String(length=40), nullable=True),
    sa.Column('karma', sa.Integer(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    mysql_character_set='utf8mb4'
    )
    op.create_index('users_hash_idx', 'users', ['user_hash'], unique=False)
    op.create_table('eventlog',
    sa.Column('eventlog_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_addr', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('app_id', sa.Text(), nullable=True),
    sa.Column('important', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('eventlog_id'),
    sa.UniqueConstraint('eventlog_id'),
    mysql_character_set='utf8mb4'
    )
    op.create_index('date_created_idx', 'eventlog', ['date_created'], unique=False)
    op.create_index('message_idx', 'eventlog', ['message'], unique=False, mysql_length=8)
    op.create_table('moderators',
    sa.Column('moderator_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('locales', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('moderator_id'),
    sa.UniqueConstraint('moderator_id'),
    mysql_character_set='utf8mb4'
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_deleted', sa.DateTime(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_addr', sa.Text(), nullable=True),
    sa.Column('user_display', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('distro', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('karma_up', sa.Integer(), nullable=True),
    sa.Column('karma_down', sa.Integer(), nullable=True),
    sa.Column('reported', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('review_id'),
    mysql_character_set='utf8mb4'
    )
    op.create_table('votes',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('val', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.review_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('vote_id'),
    mysql_character_set='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('reviews')
    op.drop_table('moderators')
    op.drop_index('message_idx', table_name='eventlog', mysql_length=8)
    op.drop_index('date_created_idx', table_name='eventlog')
    op.drop_table('eventlog')
    op.drop_index('users_hash_idx', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_taboos_locale'), table_name='taboos')
    op.drop_table('taboos')
    op.drop_table('components')
    op.drop_index('datestr', table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
