# SPDX-FileCopyrightText: 2025 Florian Müllner <fmuellner@gnome.org>
# SPDX-License-Identifier: LGPL-2.1-or-later

patterns:
  deny:
    - regex: '^[^:]+: [a-z]'
      message: "Commit message subject should be properly Capitalized. E.g. 'window: Marginalize extradicity'"
      where: subject
    - regex: '^\S*\.(js|c|h):'
      message: Commit message subject prefix should not include .c, .h etc.
      where: subject
    - regex: '([^.]\.|[:,;])\s*$'
      message: Commit message subject should not end with punctuation
      where: subject
    - regex: '^[Cc]lose[sd]?:?\s*#[0-9]+'
      message: Closes instructions must be a full link
    - regex: '^[Ff]ix(e[sd]?)?:?\s*(#[0-9]+|https://)'
      message: \"Fixes\" should be used with commits, use \"Closes\" for issues
