/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Sunday, February 5, 2023.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */
// DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED. Refer to hideventgen.sh.

#include <IOKit/hid/IOHIDEvent.h>
#include <HID/HIDEvent.h>
#include <AppleFeatures/AppleFeatures.h>

enum {

	kEventFieldDataType_None,
	kEventFieldDataType_Integer,
	kEventFieldDataType_Double,
	kEventFieldDataType_Float,
	kEventFieldDataType_IOFixed,
};

typedef struct {
	IOHIDEventField field;
	uint8_t         fieldType:6;
	uint8_t         base:1;
	uint8_t         readonly:1;
	char *          name;
} HIDEventFieldInfo;

typedef struct {
	IOHIDEventField    value;
	HIDEventFieldInfo *eventFieldDescTable;

} HIDEventFieldDescSelectorTable;
typedef struct  {
	IOHIDEventField                 value;
	HIDEventFieldDescSelectorTable *selectorTables;
} HIDSelectorTable;

typedef struct {
	IOHIDEventType     type;
	HIDEventFieldInfo *eventFieldDescTable;
	HIDSelectorTable  *selectors;
} HIDEventFieldDescTableCollection;

