image: fedora:rawhide

variables:
  DEPENDENCIES:
    libxml2-devel
    gdk-pixbuf2-devel
    libarchive-devel
    meson
    redhat-rpm-config
    gcc
    glibc-devel
    git

build_stable:
  tags:
    - crun
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build --prefix=/usr
    - ninja -C _build
    - ninja -C _build install
    - ninja -C _build dist
  artifacts:
    when: always
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs/"
      - "${CI_PROJECT_DIR}/_build/meson-dist"
      - "${CI_PROJECT_DIR}/_build/meson-private/dist-build/meson-logs/"
