/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Sunday, May 12, 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from SFACollection.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

#ifdef __cplusplus
#define SECSFAEVENTFILTER_FUNCTION extern "C" __attribute__((visibility("hidden")))
#else
#define SECSFAEVENTFILTER_FUNCTION extern __attribute__((visibility("hidden")))
#endif

__attribute__((visibility("hidden")))
@interface SECSFAEventFilter : PBCodable <NSCopying>
{
    int64_t _dropRate;
    NSString *_event;
    struct {
        uint dropRate:1;
    } _has;
}


@property (nonatomic, readonly) BOOL hasEvent;
@property (nonatomic, retain) NSString *event;

@property (nonatomic) BOOL hasDropRate;
/**
 * 0 to 100 percent propbablistic of dropping event, 0 always reporting
 * this is expressed as drop percentage, because the default is expected to be 0, and thus save space.
 */
@property (nonatomic) int64_t dropRate;

// Performs a shallow copy into other
- (void)copyTo:(SECSFAEventFilter *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(SECSFAEventFilter *)other;

SECSFAEVENTFILTER_FUNCTION BOOL SECSFAEventFilterReadFrom(__unsafe_unretained SECSFAEventFilter *self, __unsafe_unretained PBDataReader *reader);

@end

