/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Tuesday, September 3, 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from SFACollection.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

#import "SECSFAGlobalEnums.h"

@class SECSFAEventFilter;
@class SECSFAEventRule;
@class SECSFAVersionMatch;

#ifdef __cplusplus
#define SECSFARULES_FUNCTION extern "C" __attribute__((visibility("hidden")))
#else
#define SECSFARULES_FUNCTION extern __attribute__((visibility("hidden")))
#endif

__attribute__((visibility("hidden")))
@interface SECSFARules : PBCodable <NSCopying>
{
    SECSFAVersionMatch *_allowedBuilds;
    SECSFAConfigVersion _configVersion;
    NSMutableArray<SECSFAEventFilter *> *_eventFilters;
    NSMutableArray<SECSFAEventRule *> *_eventRules;
    struct {
        uint configVersion:1;
    } _has;
}


@property (nonatomic, retain) NSMutableArray<SECSFAEventRule *> *eventRules;
- (void)clearEventRules;
- (void)addEventRules:(SECSFAEventRule *)i;
- (NSUInteger)eventRulesCount;
- (SECSFAEventRule *)eventRulesAtIndex:(NSUInteger)idx;
+ (Class)eventRulesType;

@property (nonatomic, readonly) BOOL hasAllowedBuilds;
@property (nonatomic, retain) SECSFAVersionMatch *allowedBuilds;

@property (nonatomic, retain) NSMutableArray<SECSFAEventFilter *> *eventFilters;
- (void)clearEventFilters;
- (void)addEventFilter:(SECSFAEventFilter *)i;
- (NSUInteger)eventFiltersCount;
- (SECSFAEventFilter *)eventFilterAtIndex:(NSUInteger)idx;
+ (Class)eventFilterType;

@property (nonatomic) BOOL hasConfigVersion;
@property (nonatomic) SECSFAConfigVersion configVersion;
- (NSString *)configVersionAsString:(SECSFAConfigVersion)value;
- (SECSFAConfigVersion)StringAsConfigVersion:(NSString *)str;

// Performs a shallow copy into other
- (void)copyTo:(SECSFARules *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(SECSFARules *)other;

SECSFARULES_FUNCTION BOOL SECSFARulesReadFrom(__unsafe_unretained SECSFARules *self, __unsafe_unretained PBDataReader *reader);

@end

