/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Sunday, August 7, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from SFACollection.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

@class SECSFAVersion;

#ifdef __cplusplus
#define SECSFAVERSIONMATCH_FUNCTION extern "C" __attribute__((visibility("hidden")))
#else
#define SECSFAVERSIONMATCH_FUNCTION extern __attribute__((visibility("hidden")))
#endif

__attribute__((visibility("hidden")))
@interface SECSFAVersionMatch : PBCodable <NSCopying>
{
    NSMutableArray<SECSFAVersion *> *_versions;
}


@property (nonatomic, retain) NSMutableArray<SECSFAVersion *> *versions;
- (void)clearVersions;
- (void)addVersions:(SECSFAVersion *)i;
- (NSUInteger)versionsCount;
- (SECSFAVersion *)versionsAtIndex:(NSUInteger)idx;
+ (Class)versionsType;

// Performs a shallow copy into other
- (void)copyTo:(SECSFAVersionMatch *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(SECSFAVersionMatch *)other;

SECSFAVERSIONMATCH_FUNCTION BOOL SECSFAVersionMatchReadFrom(__unsafe_unretained SECSFAVersionMatch *self, __unsafe_unretained PBDataReader *reader);

@end

