/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Tuesday, December 27, 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from SFACollection.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

#import "SECSFAGlobalEnums.h"

@class SECSFAAction;

#ifdef __cplusplus
#define SECSFARULE_FUNCTION extern "C" __attribute__((visibility("hidden")))
#else
#define SECSFARULE_FUNCTION extern __attribute__((visibility("hidden")))
#endif

__attribute__((visibility("hidden")))
@interface SECSFARule : PBCodable <NSCopying>
{
    int64_t _repeatAfterSeconds;
    SECSFAAction *_action;
    SECSFAEventClass _eventClass;
    NSString *_eventType;
    NSData *_match;
    NSString *_process;
    struct {
        uint repeatAfterSeconds:1;
        uint eventClass:1;
    } _has;
}


@property (nonatomic, readonly) BOOL hasEventType;
@property (nonatomic, retain) NSString *eventType;

@property (nonatomic, readonly) BOOL hasMatch;
@property (nonatomic, retain) NSData *match;

@property (nonatomic, readonly) BOOL hasAction;
@property (nonatomic, retain) SECSFAAction *action;

@property (nonatomic) BOOL hasRepeatAfterSeconds;
@property (nonatomic) int64_t repeatAfterSeconds;

@property (nonatomic, readonly) BOOL hasProcess;
@property (nonatomic, retain) NSString *process;

@property (nonatomic) BOOL hasEventClass;
@property (nonatomic) SECSFAEventClass eventClass;
- (NSString *)eventClassAsString:(SECSFAEventClass)value;
- (SECSFAEventClass)StringAsEventClass:(NSString *)str;

// Performs a shallow copy into other
- (void)copyTo:(SECSFARule *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(SECSFARule *)other;

SECSFARULE_FUNCTION BOOL SECSFARuleReadFrom(__unsafe_unretained SECSFARule *self, __unsafe_unretained PBDataReader *reader);

@end

