/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Wednesday, January 1, 2025.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from SFACollection.proto

#import <Foundation/Foundation.h>
#import <ProtocolBuffer/PBCodable.h>

@class SECSFAPropertyValue;

#ifdef __cplusplus
#define SECSFAMATCHPROPERTY_FUNCTION extern "C" __attribute__((visibility("hidden")))
#else
#define SECSFAMATCHPROPERTY_FUNCTION extern __attribute__((visibility("hidden")))
#endif

__attribute__((visibility("hidden")))
@interface SECSFAMatchProperty : PBCodable <NSCopying>
{
    NSString *_propertyName;
    SECSFAPropertyValue *_value;
}


@property (nonatomic, readonly) BOOL hasPropertyName;
@property (nonatomic, retain) NSString *propertyName;

@property (nonatomic, readonly) BOOL hasValue;
@property (nonatomic, retain) SECSFAPropertyValue *value;

// Performs a shallow copy into other
- (void)copyTo:(SECSFAMatchProperty *)other;

// Performs a deep merge from other into self
// If set in other, singular values in self are replaced in self
// Singular composite values are recursively merged
// Repeated values from other are appended to repeated values in self
- (void)mergeFrom:(SECSFAMatchProperty *)other;

SECSFAMATCHPROPERTY_FUNCTION BOOL SECSFAMatchPropertyReadFrom(__unsafe_unretained SECSFAMatchProperty *self, __unsafe_unretained PBDataReader *reader);

@end

