/*
 *
 * Copyright (c) NeXTHub Corporation. All Rights Reserved. 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * Author: Tunjay Akbarli
 * Date: Friday, December 6, 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the ""License"");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an ""AS IS"" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Please contact NeXTHub Corporation, 651 N Broad St, Suite 201, 
 * Middletown, DE 19709, New Castle County, USA.
 *
 */

//
//  XSDHParam.h
//  CoreDaemon
//
//  Created by Mike Abbott on 9/24/2013.
//  Copyright (c) 2013 Apple Inc.  All rights reserved.
//

/*!
 * @header XSDHParam.h
 * @abstract Diffie-Hellman parameter parsing
 * @availability OS X 10.8 and later
 * @discussion Functions to read Diffie-Hellman parameters from disk files
 * @copyright 2013 Apple Inc.  All rights reserved.
 * @namespace OS X
 * @version 1.0
 */

#ifndef CoreDaemon_XSDHParam_h
#define CoreDaemon_XSDHParam_h

#include <CoreFoundation/CoreFoundation.h>
/*!
 * @function XSDHParamCreateFromFile
 *
 * @abstract
 * Read Diffie-Hellman parameters from a disk file
 *
 * @discussion
 * Reads Diffie-Hellman parameter(s) from the file.  The file must
 * contain concatenated PEM-formatted parameter(s) generated by, for
 * example, the command "openssl dhparam -2".  On success, returns an
 * array of CFData objects containing the DH parameters from the file
 * converted to DER (binary) format.  Call CFRelease() on the returned
 * array when finished.  If the file is empty, an empty array is
 * returned.  If the file cannot be read, NULL is returned.
 */
CFArrayRef XSDHParamCreateFromFile(CFStringRef path);

/*!
 * @function XSDHParamGetSize
 *
 * @abstract
 * Return the size in bits of a Diffie-Hellman parameter
 *
 * @discussion
 * Returns the size in bits (e.g. 512, 2048) of a Diffie-Hellman parameter
 * passed in DER format.  Returns 0 if the parameter cannot be parsed.
 */
CFIndex XSDHParamGetSize(CFDataRef param);

#endif
